### ISSUE TITLE
Download Sample Dataset

### ISSUE THREAD

**Issue by andydmh** [Learning-With-Purpose/Deep-ASL-Translator#1]
1. Download the 20 top classes of the [ASL LRP Dataset](http://secrets.rutgers.edu/dai/queryPages/querySelection.php).

2. Structure it using the following structure inside Python_Implementation:
 
Data -> [word1, word2, ...] -> [Front, Face, Side] -> [video1.mp4, video2.mp4, ...]

**Comment by dflorit** [comment]
A directory named dataset has been created, however, it's currently empty. As data cannot be publicly shared, it has been downloaded and shared through the project's Google Drive folder for team member's use. It can be downloaded directly from the following link: [ASLLRP Dataset](http://csr.bu.edu/asl/asllvd/annotate/index.html)

The folder currently contains 20 classes selected from the glosses with most occurrences in the dataset. The classes currently include: [Book, But, Buy, Car, Chocolate, Deaf, Finish, Future, House, In, Know, Like, Mother, Not, Really, Same, See, That, Who, Yesterday].

The structure of the folder is as follow: 
Dataset -> w1, w2, w3, ..., w20 folders -> Face, Front, Side (a folder for each) -> videos.

For now, videos including the Side and Face camera points of view have been omitted from the dataset, as we will be focusing only on the Front point of view as of right now.
