### ISSUE TITLE
Compute HOG Feature Extractors

### ISSUE THREAD

**Issue by andydmh** [Learning-With-Purpose/Deep-ASL-Translator#13]

**Comment by andydmh** [comment]
Good Explanation:
[Shah Explanation](https://www.youtube.com/watch?v=0Zib1YEE4LU)

Code Example:
`import cv2
 hog = cv2.HOGDescriptor()
 im = cv2.imread(sample)
 h = hog.compute(im)`

More Explanations:
[Get HOG image features from OpenCV + Python?](http://stackoverflow.com/questions/6090399/get-hog-image-features-from-opencv-python)

**Comment by dflorit** [comment]
methods to get the HoG features are already implemented. See preprocessing_videos.py file
