### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by andydmh** [Learning-With-Purpose/Deep-ASL-Translator#2]
1. Divide individual videos into frames. Each set of frames will be on the same path of the video inside a directory with the same name of the video after removing the .mp4 extension.

2. Crop bottom black bottom part of the frames.

**Comment by dflorit** [comment]
file preprocessing_videos.py inside tools/scripts was created to perform the video preprocessing.
videos from the sample dataset downloaded were split by frames, and each frame was cropped to remove the black section on the bottom which contained labeled information. 
The videos split by frames were saved to Google Drive, inside the dataset directory, separate from the original videos. Frames corresponding to each video were saved into a directory named in the same way as the video.
Additionally, information about each video such as length (number of frames), width, height, fps, etc, was collected, and saved into a txt file that can be found inside the dataset directory
